=== bmwieczorek/my-xml-xsd/my-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns="http://bawi.com/my-schema" targetNamespace="http://bawi.com/my-schema"
           xmlns:imported="http://bawi.com/my-imported-schema">

    <xs:import namespace="http://bawi.com/my-imported-schema" schemaLocation="my-imported-schema.xsd"/>
    <xs:include schemaLocation="my-included-schema.xsd"/>

    <xs:element name="MyRootElement">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MyStringElement" type="xs:string"/>
                <xs:element ref="MyDuplicatedElement"/>
                <xs:element name="MyDuplicatedElementWithImportedType" type="imported:MyDuplicatedElementType"/>
                <xs:element ref="imported:MyDuplicatedElement" maxOccurs="unbounded"/>
                <xs:element name="MyElementWithIncludedType" type="MyIncludedStringElementType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="MyDuplicatedElement">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="myStringAttribute"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== bmwieczorek/my-xml-xsd/my-xml.xml
<?xml version="1.0" encoding="UTF-8" ?>
<MyRootElement xmlns="http://bawi.com/my-schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.bawi.com/my-schema my-schema.xsd"
               xmlns:imp="http://bawi.com/my-imported-schema">

    <MyStringElement>Text</MyStringElement>
    <MyDuplicatedElement myStringAttribute="aaa">AAA</MyDuplicatedElement>

    <!-- Element name defined in parent schema but type imported -->
    <MyDuplicatedElementWithImportedType myImportedIntAttribute="abc">ABC</MyDuplicatedElementWithImportedType>

    <!-- elements imported by ref with namespace change to imp -->
    <imp:MyDuplicatedElement myImportedIntAttribute="222">BBB</imp:MyDuplicatedElement>
    <MyDuplicatedElement xmlns="http://bawi.com/my-imported-schema" myImportedIntAttribute="333">CCC</MyDuplicatedElement>
    <i:MyDuplicatedElement xmlns:i="http://bawi.com/my-imported-schema" myImportedIntAttribute="444">DDD</i:MyDuplicatedElement>

    <!-- Element name defined in parent schema but type included -->
    <MyElementWithIncludedType myIncludedIntAttribute="555">EEE</MyElementWithIncludedType>
</MyRootElement>
